apiVersion: v1
kind: Secret
metadata:
  name: efp-portal-secret
  namespace: default
stringData:
  BOOTSTRAP_ADMIN_PASSWORD: ""
  PORTAL_INTERNAL_API_KEY: ""
  RUNTIME_INTERNAL_API_KEY: ""
  GIT_USERNAME: ""
  GIT_TOKEN: ""
