apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: efp-portal-ingress
  namespace: default
  labels:
    app: efp-portal-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: efp-portal-service
                port:
                  number: 80