apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efp-portal-storage
provisioner: kubernetes.io/no-provisioner
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efp-efs-portal-pv
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efp-portal-storage
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/portal
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efp-portal-efs-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: efp-portal-storage
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efp-agents-storage
provisioner: kubernetes.io/no-provisioner
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efp-efs-agents-pv
  namespace: efp-agents
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efp-agents-storage
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/agents
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efp-agents-efs-pvc
  namespace: efp-agents
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: efp-agents-storage