kind: Service
metadata:
  name: portal
  namespace: default
  labels:
    app: portal
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: portal
apiVersion: apps/v1
kind: Deployment
